### ISSUE TITLE
[BUG] Install via requirements.txt fails at `logging` package

### ISSUE THREAD

**Issue by martinkou** [pkweitai/hummingbotAI#5]
The logging package shouldn't be necessary anyway, since it's built-in with Python. Here's what I'm seeing with `pip install -r requirements.txt`

```
Collecting logging==0.4.9.6 (from -r requirements.txt (line 108))
  Downloading logging-0.4.9.6.tar.gz (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.0/96.0 kB 244.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/home/martin_kou/anaconda3/envs/hummingbot-ai/lib/python3.11/site-packages/setuptools/__init__.py", line 8, in <module>
          import _distutils_hack.override  # noqa: F401
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/martin_kou/anaconda3/envs/hummingbot-ai/lib/python3.11/site-packages/_distutils_hack/override.py", line 1, in <module>
          __import__('_distutils_hack').do_override()
        File "/home/martin_kou/anaconda3/envs/hummingbot-ai/lib/python3.11/site-packages/_distutils_hack/__init__.py", line 70, in do_override
          ensure_local_distutils()
        File "/home/martin_kou/anaconda3/envs/hummingbot-ai/lib/python3.11/site-packages/_distutils_hack/__init__.py", line 56, in ensure_local_distutils
          core = importlib.import_module('distutils.core')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/martin_kou/anaconda3/envs/hummingbot-ai/lib/python3.11/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/martin_kou/anaconda3/envs/hummingbot-ai/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 13, in <module>
          from .cmd import Command
        File "/home/martin_kou/anaconda3/envs/hummingbot-ai/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 7, in <module>
          import logging
        File "/tmp/pip-install-cbvukfmh/logging_62d62e57563b4342aa8b23317dfc21d3/logging/__init__.py", line 618
          raise NotImplementedError, 'emit must be implemented '\
                                   ^
      SyntaxError: invalid syntax
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Removing the `logging==0.4.9.6` line from `requirements.txt` fixes the issue for me.

**Comment by pkweitai** [comment]
fixed
